apiVersion: v1
kind: Service
metadata:
  name: bd-scraper-balancer
spec:
  selector:
    app: bd-scraper
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-scraper
spec:
  selector:
    matchLabels:
      app: bd-scraper
  replicas: 1
  template:
    metadata:
      labels:
        app: bd-scraper
    spec:
      containers:
      - name: bd-scraper
        image: hub.osrsbotdetector.com/bot-detector/bd-scraper:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000