version: '3'
services:
  mysql:
    build:
      context: ../bot-detector-mysql
      dockerfile: Dockerfile
    image: bot-detector/bd-mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_bot_buster
      - MYSQL_USER=botssuck
      - MYSQL_PASSWORD=botdetector
    volumes:
      - ../bot-detector-mysql/mount:/var/lib/mysql
      - '../bot-detector-mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    ports:
      - "3306:3306"
    networks:
      - botdetector-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        root_path: /
        api_port: 5000
    image: bot-detector/bd-api:latest
    environment:
      - sql_uri=mysql+asyncmy://root:root_bot_buster@mysql:3306/playerdata
      - discord_sql_uri=mysql+asyncmy://root:root_bot_buster@mysql:3306/discord
      - token=verify_ban
    volumes:
      - '../Bot-Detector-Core-Files/api:/code/api'
    ports:
      - "5000:5000"
    networks:
      - botdetector-network
    depends_on:
      - mysql
      
  scraper:
    build:
      context: ../bot-detector-scraper
      dockerfile: Dockerfile
    image: bot-detector/bd-scraper:latest
    environment:
    # free 10 proxies from https://www.webshare.io/?referral_code=6c2ftu5hdkxp
    # you can find the proxy url at Proxy > List > Export https://proxy.webshare.io/proxy/list?
      - PROXY_DOWNLOAD_URL=<YourProxyList>
      - TOKEN=verify_ban
      - QUERY_SIZE=100
      - endpoint=127.0.0.1:5000
    # env_file:
    #   - .env
    networks:
      - botdetector-network
    depends_on:
      - api

networks:
  botdetector-network:
