version: '3'
services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: bd-scraper
    command: "python src/main.py"
    # command: sleep infinity
    env_file:
      - .env
