apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-scraper
spec:
  selector:
    matchLabels:
      app: bd-scraper
  replicas: 1
  template:
    metadata:
      labels:
        app: bd-scraper
    spec:
      containers:
      - name: bd-scraper
        image: hub.osrsbotdetector.com/bot-detector/bd-scraper:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
          limits:
            cpu: "750m"
            memory: "1000Mi"
      imagePullSecrets:
      - name: regcred
