name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set Up ENV
      run: |
          echo "${{ secrets.API_TOKEN }}" > .env
          echo "${{ secrets.ENDPOINT }}" >> .env
          echo "${{ secrets.PROXY_DOWNLOAD_URL }}" >> .env
          echo "${{ secrets.QUERY_SIZE }}" >> .env
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t bot-detector/bd-scraper:latest

    - name: Tag Image
      run: docker tag bot-detector/bd-scraper:latest hub.osrsbotdetector.com/bot-detector/bd-scraper:latest
      
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login https://hub.osrsbotdetector.com -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin

    - name: Push Image to Registry
      run: docker push bot-detector/bd-scraper:latest